name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    name: Java ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 11 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: mvn -B package
